global:
  scrape_interval: 1m
  evaluation_interval: 1m

scrape_configs:
#### Node Linux ####
  - job_name: "node-linux"
    ec2_sd_configs: &ec2config
      - region: "ap-south-1"
    relabel_configs:
      - source_labels: [__meta_ec2_tag_OS]
        regex: linux
        action: keep
      - source_labels: [__meta_ec2_private_ip]
        regex: '(.*)'
        replacement: '${1}:1784'
        target_label: __address__
      - source_labels: [__meta_ec2_tag_Name]
        target_label: instance_name
      - target_label: "Organisation_Id"
        replacement: "000"
      - target_label: "raiseOnBehalfOf"
        replacement: "ms-monitoring@minfytech.com"
      - target_label: "IncidentTypeIdTI"
        replacement: "4702"
      - target_label: "IncidentTypeIdCI"
        replacement: "4702"
      - target_label: "serviceRequestTypeIdCU"
        replacement: "4702"
      - target_label: "JiraProjectIdTI"
        replacement: "2113"
      - target_label: "JiraProjectIdCI"
        replacement: "2113"
      - target_label: "JiraProjectIdCU"
        replacement: "2113"
      - target_label: "projectKeyTI"
        replacement: "AT"
      - target_label: "projectKeyCI"
        replacement: "AT"
      - target_label: "ProjectKeyCU"
        replacement: "AT"
      - target_label: "SearchInProjects"
        replacement: "AT"
      - target_label: "ClientName"
        replacement: "<insert_client_name>"
      - target_label: "cust_email_id"
        replacement: "<insert_email1, insert_email2>"

#### Node-Windows ####
  - job_name: "node-windows"
    ec2_sd_configs: *ec2config
    relabel_configs:
      - source_labels: [__meta_ec2_tag_OS]
        regex: windows
        action: keep
      - source_labels: [__meta_ec2_private_ip]
        regex: '(.*)'
        replacement: '${1}:9182'
        target_label: __address__
      - source_labels: [__meta_ec2_tag_Name]
        target_label: instance_name
      - target_label: "Organisation_Id"
        replacement: "000"
      - target_label: "raiseOnBehalfOf"
        replacement: "ms-monitoring@minfytech.com"
      - target_label: "IncidentTypeIdTI"
        replacement: "4702"
      - target_label: "IncidentTypeIdCI"
        replacement: "4702"
      - target_label: "serviceRequestTypeIdCU"
        replacement: "4702"
      - target_label: "JiraProjectIdTI"
        replacement: "2113"
      - target_label: "JiraProjectIdCI"
        replacement: "2113"
      - target_label: "JiraProjectIdCU"
        replacement: "2113"
      - target_label: "projectKeyTI"
        replacement: "AT"
      - target_label: "projectKeyCI"
        replacement: "AT"
      - target_label: "ProjectKeyCU"
        replacement: "AT"
      - target_label: "SearchInProjects"
        replacement: "AT"
      - target_label: "ClientName"
        replacement: "<insert_client_name>"
      - target_label: "cust_email_id"
        replacement: "<insert_email1, insert_email2>"

#### YACE ####
  - job_name: "yace"
    static_configs:
      - targets: ["127.0.0.1:8099"]

#### BlackBox ####
#   - job_name: 'blackbox'
#     metrics_path: /probe
#     params:
#       module: [http_2xx]  # Look for a HTTP 200 response.
#     static_configs:
#       - targets:
#           - http://prometheus.io    # Target to probe with http.
#           - https://prometheus.io   # Target to probe with https.
#           - http://3.6.160.30:80  # Target to probe with http on port 8080.
#           - https://www.youtube.com/
#           - https://aws.amazon.com/
#     relabel_configs:
#       - source_labels: [__address__]
#         target_label: __param_target
#       - source_labels: [__param_target]
#         target_label: instance
#       - target_label: __address__
#         replacement: blackbox:9115
#       - target_label: "Organisation_Id"
#         replacement: "000"
#       - target_label: "raiseOnBehalfOf"
#         replacement: "ms-monitoring@minfytech.com"
#       - target_label: "IncidentTypeIdTI"
#         replacement: "4702"
#       - target_label: "IncidentTypeIdCI"
#         replacement: "4702"
#       - target_label: "serviceRequestTypeIdCU"
#         replacement: "4702"
#       - target_label: "JiraProjectIdTI"
#         replacement: "2113"
#       - target_label: "JiraProjectIdCI"
#         replacement: "2113"
#       - target_label: "JiraProjectIdCU"
#         replacement: "2113"
#       - target_label: "projectKeyTI"
#         replacement: "AT"
#       - target_label: "projectKeyCI"
#         replacement: "AT"
#       - target_label: "ProjectKeyCU"
#         replacement: "AT"
#       - target_label: "SearchInProjects"
#         replacement: "AT"
#       - target_label: "ClientName"
#         replacement: "<insert_client_name>"
#       - target_label: "cust_email_id"
#         replacement: "<insert_email1, insert_email2>"


# #### Blackbox Operational ####  
#   - job_name: 'blackbox_exporter'  #blackbox exporter's operational metrics.
    static_configs:
      - targets: ['127.0.0.1:9115']

### Rule Files ####
rule_files:
  - "/etc/prometheus/EC2-Alerts.yml"
  - "/etc/prometheus/RDS-Alerts.yml"
  - "/etc/prometheus/URL-Alerts.yml"

#### AlertManager ####
alerting:
  alertmanagers:
    - static_configs:
      - targets: ["127.0.0.1:9093"]